---
Name: SSCustomPageWithContactUsForm
---
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - SSCustomPageWithContactUsForm\ContactUsController
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - CustomPageLayoutConfig